### ISSUE TITLE
Proper documentation about dependent packages and running instruction needed.

### ISSUE THREAD

**Issue by Luckykantnayak** [pvandervelde/zinger_nav#4]
@pvandervelde  Kindly provide proper instructions about the package dependencies and the sequence of commands in each terminal needed for navigation. For example the rviz package is not mentioned in the README , the command for localization and a default map to use is not there.

**Comment by pvandervelde** [comment]
Hi @Luckykantnayak 

I've created PR #5 to add a reference to zinger_ignition in the readme and also added a note to indicate that localization has not been properly configured for this repository (or tested at all). Therefore I cannot provide a default map at the moment.

Additionally I've created pvandervelde/zinger_ignition#3 to point out that you need the `zinger_viz` package if you want to run RViz.

If you have some time please have a look at these PRs and let me know if they resolve your issues.

**Comment by pvandervelde** [comment]
Merged PRs.
